# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'datadb' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for datadb
  pod 'FMDB'
  pod 'JQFMDB'

  target 'datadbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'datadbUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
